### ISSUE TITLE
jspc ls YCM

### ISSUE THREAD

**Issue by coachshea** [othree/jspc.vim#5]
I have recently began using your plugin in conjunction with YouCompleteme on livescript files. I absolutely love the completions that this plugin  supplies, but when I try to complete something provided by the default omnifunction (if your not familiar livescript defaults to javascript#complete), I receive errors.

for example: if I type document.get<ctrl-space>, I receive the following error message:

Error detected while processing function jspc#omni:
line    6:
E121: Undefined variable: w:jspc_omnifunc
Error detected while processing function jspc#omni:
line    6:
E15: Invalid expression: w:jspc_omnifunc != ''
Error detected while processing function jspc#omni:
line   15:
E121: Undefined variable: w:jspc_omnifunc
Error detected while processing function jspc#omni:

Any help is greatly appreciated

**Comment by othree** [comment]
Looks like this file is not executed

    https://github.com/othree/jspc.vim/blob/master/after/ftplugin/ls.vim

**Comment by coachshea** [comment]
You were right. Thanks for the help. It's embarrassing how I managed to screw this up, but it's working perfectly now.

**Comment by coachshea** [comment]
f
